<?php

namespace App\Repository;

//use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
}
